name: 'alpaca_analysis'
version: '1.0.0'
config-version: 2

profile: 'alpaca_analysis'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_review_analysis:
    +materialized: table
    +schema: alpaca_review_analysis  # Output schema