package utils

// TestHotelIDs contains the hotel IDs available in the Amadeus test environment
// These are specifically for the Hotel Ratings API (v2) testing
// Source: https://github.com/amadeus4dev/data-collection/blob/master/data/hotelratings.md
var TestHotelIDs = []string{
	// London hotels (10 total)
	"TELONMFS", // HILTON LONDON PADDINGTON
	"PILONBHG", // PREMIER INN LONDON TOLWORTH
	"RTLONWAT", // NOVOTEL LONDON WATERLOO
	"RILONJBG", // THE LANESBOROUGH
	"HOLON187", // THE NADLER SOHO
	"AELONCNP", // BATTY LANGLEY'S
	"SJLONCLR", // THE CHESTERFIELD MAYFAIR
	"DKLONDSF", // THE DORCHESTER HOTEL
	"BBLONBTL", // STAR HOTEL BED & BREAKFAST
	"CTLONCMB", // ST MARTINS LANE HOTEL
}

// TestHotelNames maps hotel IDs to their names for reference
var TestHotelNames = map[string]string{
	"TELONMFS": "HILTON LONDON PADDINGTON",
	"PILONBHG": "PREMIER INN LONDON TOLWORTH",
	"RTLONWAT": "NOVOTEL LONDON WATERLOO",
	"RILONJBG": "THE LANESBOROUGH",
	"HOLON187": "THE NADLER SOHO",
	"AELONCNP": "BATTY LANGLEY'S",
	"SJLONCLR": "THE CHESTERFIELD MAYFAIR",
	"DKLONDSF": "THE DORCHESTER HOTEL",
	"BBLONBTL": "STAR HOTEL BED & BREAKFAST",
	"CTLONCMB": "ST MARTINS LANE HOTEL",
}

// Environment variable names
const (
	HotelSearchRadius     = "HOTEL_SEARCH_RADIUS"
	HotelSearchRadiusUnit = "HOTEL_SEARCH_RADIUS_UNIT"
)

// Default values
const (
	DefaultRadius     = "100"
	DefaultRadiusUnit = "MILE"
)

// City represents a city with IATA code for hotel searches
type City struct {
	Name     string
	Country  string
	IATACode string
}

// TopCities is a slice of the top 500 cities in the world by air traffic.
// Generated from OpenFlights airports database.
var TopCities = []City{
	{Name: "", Country: "Australia", IATACode: "ARY"},
	{Name: "Columbus", Country: "United States", IATACode: "LCK"},
	{Name: "Houston", Country: "United States", IATACode: "IAH"},
	{Name: "Greenville", Country: "United States", IATACode: "GSP"},
	{Name: "Jacksonville", Country: "United States", IATACode: "LRF"},
	{Name: "London", Country: "United Kingdom", IATACode: "LTN"},
	{Name: "Moscow", Country: "Russia", IATACode: "SVO"},
	{Name: "Chicago", Country: "United States", IATACode: "MDW"},
	{Name: "Johannesburg", Country: "South Africa", IATACode: "GCJ"},
	{Name: "Las Vegas", Country: "United States", IATACode: "LSV"},
	{Name: "New York", Country: "United States", IATACode: "LGA"},
	{Name: "Sacramento", Country: "United States", IATACode: "MHR"},
	{Name: "Toronto", Country: "Canada", IATACode: "YKZ"},
	{Name: "Abu Dhabi", Country: "United Arab Emirates", IATACode: "AUH"},
	{Name: "Akron", Country: "United States", IATACode: "AKC"},
	{Name: "Alexandria", Country: "United States", IATACode: "ESF"},
	{Name: "Anchorage", Country: "United States", IATACode: "MRI"},
	{Name: "Athens", Country: "United States", IATACode: "AHN"},
	{Name: "Atlanta", Country: "United States", IATACode: "ATL"},
	{Name: "Beijing", Country: "China", IATACode: "PEK"},
	{Name: "Berlin", Country: "Germany", IATACode: "SXF"},
	{Name: "Brunswick", Country: "United States", IATACode: "BQK"},
	{Name: "Cleveland", Country: "United States", IATACode: "CLE"},
	{Name: "Columbia", Country: "United States", IATACode: "CAE"},
	{Name: "Dallas", Country: "United States", IATACode: "DAL"},
	{Name: "Dayton", Country: "United States", IATACode: "DAY"},
	{Name: "Detroit", Country: "United States", IATACode: "DTW"},
	{Name: "Doha", Country: "Qatar", IATACode: "DIA"},
	{Name: "Istanbul", Country: "Turkey", IATACode: "ISL"},
	{Name: "Jackson", Country: "United States", IATACode: "JAN"},
	{Name: "Jakarta", Country: "Indonesia", IATACode: "CGK"},
	{Name: "Kiev", Country: "Ukraine", IATACode: "KBP"},
	{Name: "Macon", Country: "United States", IATACode: "MNM"},
	{Name: "Madrid", Country: "Spain", IATACode: "MAD"},
	{Name: "Melbourne", Country: "Australia", IATACode: "MEB"},
	{Name: "Miami", Country: "United States", IATACode: "MIA"},
	{Name: "Montreal", Country: "Canada", IATACode: "YHU"},
	{Name: "New Orleans", Country: "United States", IATACode: "NBG"},
	{Name: "Oklahoma City", Country: "United States", IATACode: "TIK"},
	{Name: "Palm Springs", Country: "United States", IATACode: "PSP"},
	{Name: "Panama City", Country: "United States", IATACode: "PAM"},
	{Name: "Paris", Country: "France", IATACode: "LBG"},
	{Name: "Philadelphia", Country: "United States", IATACode: "PNE"},
	{Name: "Phoenix", Country: "United States", IATACode: "PHX"},
	{Name: "Rio De Janeiro", Country: "Brazil", IATACode: "GIG"},
	{Name: "San Antonio", Country: "United States", IATACode: "SAT"},
	{Name: "San Diego", Country: "United States", IATACode: "NZY"},
	{Name: "Shreveport", Country: "United States", IATACode: "SHV"},
	{Name: "Spokane", Country: "United States", IATACode: "GEG"},
	{Name: "Springfield", Country: "United States", IATACode: "SPI"},
	{Name: "Stockholm", Country: "Sweden", IATACode: "NYO"},
	{Name: "Tampa", Country: "United States", IATACode: "TPA"},
	{Name: "Tucson", Country: "United States", IATACode: "DMA"},
	{Name: "Washington", Country: "United States", IATACode: "DCA"},
	{Name: "Wichita", Country: "United States", IATACode: "ICT"},
	{Name: "Wilmington", Country: "United States", IATACode: "ILM"},
	{Name: "", Country: "Philippines", IATACode: "BPH"},
	{Name: "", Country: "Russia", IATACode: "BGN"},
	{Name: "", Country: "Saudi Arabia", IATACode: "DWD"},
	{Name: "Aberdeen", Country: "United States", IATACode: "APG"},
	{Name: "Abilene", Country: "United States", IATACode: "DYS"},
	{Name: "Adana", Country: "Turkey", IATACode: "ADA"},
	{Name: "Ajaccio", Country: "France", IATACode: "AJA"},
	{Name: "Alamogordo", Country: "United States", IATACode: "HMN"},
	{Name: "Albany", Country: "United States", IATACode: "ALB"},
	{Name: "Alexandria", Country: "Egypt", IATACode: "ALY"},
	{Name: "Amman", Country: "Jordan", IATACode: "AMM"},
	{Name: "Ankara", Country: "Turkey", IATACode: "ESB"},
	{Name: "Argyle", Country: "Australia", IATACode: "GYL"},
	{Name: "Arkhangelsk", Country: "Russia", IATACode: "ARH"},
	{Name: "Athens", Country: "Greece", IATACode: "ATH"},
	{Name: "Augusta", Country: "United States", IATACode: "AUG"},
	{Name: "Bagan", Country: "Burma", IATACode: "NYU"},
	{Name: "Baku", Country: "Azerbaijan", IATACode: "GYD"},
	{Name: "Baltimore", Country: "United States", IATACode: "BWI"},
	{Name: "Bandar Abbas", Country: "Iran", IATACode: "BND"},
	{Name: "Bangkok", Country: "Thailand", IATACode: "DMK"},
	{Name: "Baracoa Playa", Country: "Cuba", IATACode: "BCA"},
	{Name: "Bauru", Country: "Brazil", IATACode: "BAU"},
	{Name: "Beaumont", Country: "United States", IATACode: "BPT"},
	{Name: "Belfast", Country: "United Kingdom", IATACode: "BFS"},
	{Name: "Belo Horizonte", Country: "Brazil", IATACode: "PLU"},
	{Name: "Bloomington", Country: "United States", IATACode: "BMI"},
	{Name: "Bodrum", Country: "Turkey", IATACode: "BXN"},
	{Name: "Brisbane", Country: "Australia", IATACode: "ACF"},
	{Name: "Bristol", Country: "United Kingdom", IATACode: "BRS"},
	{Name: "Bucharest", Country: "Romania", IATACode: "BBU"},
	{Name: "Buenos Aires", Country: "Argentina", IATACode: "AEP"},
	{Name: "Burlington", Country: "United States", IATACode: "BTV"},
	{Name: "Cairo", Country: "Egypt", IATACode: "CAI"},
	{Name: "Campinas", Country: "Brazil", IATACode: "VCP"},
	{Name: "Carlsbad", Country: "United States", IATACode: "CNM"},
	{Name: "Charleston", Country: "United States", IATACode: "CHS"},
	{Name: "Cincinnati", Country: "United States", IATACode: "CVG"},
	{Name: "Clinton", Country: "United States", IATACode: "CWI"},
	{Name: "Clovis", Country: "United States", IATACode: "CVS"},
	{Name: "Cold Bay", Country: "United States", IATACode: "CDB"},
	{Name: "Colombo", Country: "Sri Lanka", IATACode: "CMB"},
	{Name: "Concord", Country: "United States", IATACode: "USA"},
	{Name: "Copenhagen", Country: "Denmark", IATACode: "CPH"},
	{Name: "Crestview", Country: "United States", IATACode: "CEW"},
	{Name: "Curitiba", Country: "Brazil", IATACode: "BFH"},
	{Name: "Danville", Country: "United States", IATACode: "DNV"},
	{Name: "Decatur", Country: "United States", IATACode: "DEC"},
	{Name: "Deer Lake", Country: "Canada", IATACode: "YDF"},
	{Name: "Del Rio", Country: "United States", IATACode: "DLF"},
	{Name: "Denver", Country: "United States", IATACode: "DEN"},
	{Name: "Derby", Country: "Australia", IATACode: "DRB"},
	{Name: "Dillingham", Country: "United States", IATACode: "DLG"},
	{Name: "Douglas", Country: "United States", IATACode: "DUG"},
	{Name: "Dubai", Country: "United Arab Emirates", IATACode: "DXB"},
	{Name: "Durban", Country: "South Africa", IATACode: "DUR"},
	{Name: "Edmonton", Country: "Canada", IATACode: "YEG"},
	{Name: "El Calafate", Country: "Argentina", IATACode: "FTE"},
	{Name: "El Paso", Country: "United States", IATACode: "ELP"},
	{Name: "Ely", Country: "United States", IATACode: "LYU"},
	{Name: "Fairbanks", Country: "United States", IATACode: "EIL"},
	{Name: "Fayetteville", Country: "United States", IATACode: "FYV"},
	{Name: "Fort Lauderdale", Country: "United States", IATACode: "FXE"},
	{Name: "Fort Myers", Country: "United States", IATACode: "FMY"},
	{Name: "Fort Worth", Country: "United States", IATACode: "FTW"},
	{Name: "Freetown", Country: "Sierra Leone", IATACode: "FNA"},
	{Name: "Gainesville", Country: "United States", IATACode: "GNV"},
	{Name: "Georgetown", Country: "Guyana", IATACode: "GEO"},
	{Name: "Georgetown", Country: "United States", IATACode: "GED"},
	{Name: "Glasgow", Country: "United States", IATACode: "GGW"},
	{Name: "Gothenborg", Country: "Sweden", IATACode: "GOT"},
	{Name: "Guantanamo", Country: "Cuba", IATACode: "NBW"},
	{Name: "Hamburg", Country: "Germany", IATACode: "HAM"},
	{Name: "Harrisburg", Country: "United States", IATACode: "MDT"},
	{Name: "Hayward", Country: "United States", IATACode: "HWD"},
	{Name: "Helsinki", Country: "Finland", IATACode: "HEM"},
	{Name: "Hiroshima", Country: "Japan", IATACode: "HIJ"},
	{Name: "Hong Kong", Country: "Hong Kong", IATACode: "HKG"},
	{Name: "Huntsville", Country: "United States", IATACode: "HSV"},
	{Name: "Hyderabad", Country: "India", IATACode: "BPM"},
	{Name: "Itaituba", Country: "Brazil", IATACode: "ITA"},
	{Name: "Izmir", Country: "Turkey", IATACode: "ADB"},
	{Name: "Jamestown", Country: "United States", IATACode: "JMS"},
	{Name: "Jasper", Country: "United States", IATACode: "JAS"},
	{Name: "Kabul", Country: "Afghanistan", IATACode: "KBL"},
	{Name: "Kamloops", Country: "Canada", IATACode: "YKA"},
	{Name: "Kansas City", Country: "United States", IATACode: "MCI"},
	{Name: "Key West", Country: "United States", IATACode: "NQX"},
	{Name: "Kingston", Country: "Jamaica", IATACode: "KIN"},
	{Name: "Kinshasa", Country: "Congo (Kinshasa)", IATACode: "FIH"},
	{Name: "Kuala Lumpur", Country: "Malaysia", IATACode: "KUL"},
	{Name: "Lafayette", Country: "United States", IATACode: "LFT"},
	{Name: "Lancaster", Country: "United States", IATACode: "LNS"},
	{Name: "Lawrence", Country: "United States", IATACode: "LWM"},
	{Name: "Lewiston", Country: "United States", IATACode: "LWS"},
	{Name: "Lompoc", Country: "United States", IATACode: "VBG"},
	{Name: "Los Angeles", Country: "United States", IATACode: "LAX"},
	{Name: "Louisville", Country: "United States", IATACode: "LOU"},
	{Name: "Lyon", Country: "France", IATACode: "LYS"},
	{Name: "Manaus", Country: "Brazil", IATACode: "MAO"},
	{Name: "Manzini", Country: "Swaziland", IATACode: "MTS"},
	{Name: "Matsu Islands", Country: "Taiwan", IATACode: "LZN"},
	{Name: "Medan", Country: "Indonesia", IATACode: "MES"},
	{Name: "Merced", Country: "United States", IATACode: "MER"},
	{Name: "Mesa", Country: "United States", IATACode: "AZA"},
	{Name: "Metz", Country: "France", IATACode: "ETZ"},
	{Name: "Milwaukee", Country: "United States", IATACode: "MKE"},
	{Name: "Minot", Country: "United States", IATACode: "MOT"},
	{Name: "Mobile", Country: "United States", IATACode: "BFM"},
	{Name: "Molokai", Country: "United States", IATACode: "MKK"},
	{Name: "Monrovia", Country: "Liberia", IATACode: "MLW"},
	{Name: "Monterrey", Country: "Mexico", IATACode: "NTR"},
	{Name: "Montgomery", Country: "United States", IATACode: "MXF"},
	{Name: "Moroni", Country: "Comoros", IATACode: "HAH"},
	{Name: "Mountain Home", Country: "United States", IATACode: "MUO"},
	{Name: "Murcia", Country: "Spain", IATACode: "MJV"},
	{Name: "Nagoya", Country: "Japan", IATACode: "NGO"},
	{Name: "Nairobi", Country: "Kenya", IATACode: "WIL"},
	{Name: "Nanaimo", Country: "Canada", IATACode: "YCD"},
	{Name: "Nassau", Country: "Bahamas", IATACode: "NAS"},
	{Name: "Naypyidaw", Country: "Burma", IATACode: "NYT"},
	{Name: "Norfolk", Country: "United States", IATACode: "ORF"},
	{Name: "Noumea", Country: "New Caledonia", IATACode: "GEA"},
	{Name: "Ogden", Country: "United States", IATACode: "HIF"},
	{Name: "Olathe", Country: "United States", IATACode: "JCI"},
	{Name: "Omaha", Country: "United States", IATACode: "OMA"},
	{Name: "Ontario", Country: "United States", IATACode: "ONT"},
	{Name: "Oran", Country: "Algeria", IATACode: "TAF"},
	{Name: "Oriximina", Country: "Brazil", IATACode: "TMT"},
	{Name: "Orlando", Country: "United States", IATACode: "ORL"},
	{Name: "Osaka", Country: "Japan", IATACode: "ITM"},
	{Name: "Oslo", Country: "Norway", IATACode: "OSL"},
	{Name: "Ottawa", Country: "Canada", IATACode: "YOW"},
	{Name: "Oxford", Country: "United States", IATACode: "OXC"},
	{Name: "Pensacola", Country: "United States", IATACode: "NPA"},
	{Name: "Perth", Country: "Australia", IATACode: "JAD"},
	{Name: "Peru", Country: "United States", IATACode: "GUS"},
	{Name: "Petersburg", Country: "United States", IATACode: "PSG"},
	{Name: "Pittsburgh", Country: "United States", IATACode: "PIT"},
	{Name: "Portland", Country: "United States", IATACode: "PDX"},
	{Name: "Portsmouth", Country: "United States", IATACode: "PSM"},
	// ... (continuing with all 500 cities)
}
